name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check PHP syntax
      run: |
        find . -type f -name '*.php' -not -path '*/vendor/*' | \
        while read file; do php -l "$file" || exit 1; done
