name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: PHP Syntax Check
        run: |
          find . -type f -name "*.php" ! -path "./vendor/*" | while IFS= read -r file; do
            php -l "$file" || exit 1
          done
