name: WordPress Coding Standards
on: [push, pull_request]

jobs:
  wpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Install dependencies
        run: |
          composer global require squizlabs/php_codesniffer
          composer global require wp-coding-standards/wpcs
          composer global require dealerdirect/phpcodesniffer-composer-installer
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH
          
      - name: Run WordPress Coding Standards
        run: |
          phpcs -i
          phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* .
